version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 15
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@11.2.6
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --prod
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/github-s3-angular-app/ s3://girishgodage-demo-app-2021 --delete